version: 3

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of GreenWeez / we have one row per product_id found in each orders_id
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"  # The timestamp field representing when the data was loaded
        freshness:
          warn_after: {count: 90, period: day}  # Warning if data is older than 90 days
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: the unique identifier of the orders
          - name: pdt_id
            description: the unique identifier of the products
          - name: revenue
            description: the revenue made from the orders
          - name: quantity
            description: amount of the product bought in the order
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - orders_id
                - pdt_id
      - name: product
        identifier: raw_gz_product
        description: products of GreenWeez / we have one row per product_id representing each product
        columns:
          - name: products_id
            description: the unique identifier of the products
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: the price of the product
      - name: ship
        identifier: raw_gz_ship
        description: the shipping details of each order in GreenWeez / we have one row per orders_id representing each order
        columns:
          - name: orders_id
            description: the unique identifier of the orders
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the shipping fee of the order
          - name: logCost
            description: the cost of the logistics of the order
          - name: ship_cost
            description: the cost incurred by the shipping of the order
